# Add enviroment variables here

POSTGRES_USER: <your-psql-username>
POSTGRES_PASSWORD: <your-psql-password>
POSTGRES_HOST: <your-psql-host>

POSTGRES_DEVELOPMENT_DB: dinorun_development
POSTGRES_TEST_DB: dinorun_test
POSTGRES_DB: dinorun
RAILS_SERVE_STATIC_FILES: true
SPOTIFY_ID: <your-spotify-app-id>
SPOTIFY_SECRET: <your-spotify-app-secret>
RAILS_MASTER_KEY: <your-rails-master-key>